language: node_js
node_js:
  - '12.15'

cache:
  directories:
    - node_modules

script:
  - yarn run lint
  - CI=true yarn run test --coverage 
  - bash <(curl -s https://codecov.io/bash) -t 8b45a2e4-4ae6-433f-a2bb-0a325cd3d21a

before_deploy:
  - yarn run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: build
    on:
      branch: master
