language: node_js
node_js:
  - '12.15'

cache:
  directories:
    - node_modules

script:
  - yarn run lint
  - CI=true yarn run test --coverage 
  - bash <(curl -s https://codecov.io/bash) -t 2a58f71f-c71d-4f64-b1da-6106a0dc7e87

before_deploy:
  - yarn run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: build
    on:
      branch: master