#####################################################################
# Codecov configuration.
#####################################################################
ignore:
    - "**/etc/.*"
    - "lib/*.js"
    - "src/shared/generated"
    