version: '3'

services:
    apps:
        build:
            context: ./
            dockerfile: ./etc/docker/Dockerfile
        container_name: react-movie-frontend
        volumes:
            - .:/usr/src/react-movie/
            - ./.eslintrc:/usr/src/react-movie/.eslintrc
            - ./package.json:/usr/src/react-movie/package.json
            - ./tsconfig.json:/usr/src/react-movie/tsconfig.json
            - ./node_modules:/usr/src/react-movie/node_modules
            - ./.eslintignore:/usr/src/react-movie/.eslintignore
        command: yarn start
        ports:
            - 3000:3000
        expose:
            - 3000
        networks:
            - internal

networks:
    internal:
        driver: bridge